AllCops:
  TargetRubyVersion: 2.5.0

Metrics/LineLength:
  Max: 200

Metrics/MethodLength:
  Max: 30

Security/Open:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
